# Generated by Django 3.0.2 on 2020-01-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista_telefonica', '0002_anuncio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='nome_da_empresa',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='anuncio',
            old_name='telefone_de_contato',
            new_name='telefone',
        ),
    ]
